services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
